version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:2.15.1-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: xnessdbdev
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data: