import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased fixed w-screen`}>
				{children}
				<Toaster
					position="bottom-right"
					toastOptions={{
						style: {
							background: "#0a0a0a",
							color: "#fff",
							borderRadius: "9px",
							backdropFilter: "blur(5px)",
							WebkitBackdropFilter: "blur(10px) saturate(150%)", // Safari
			
							
						},
					}}
				/>
			</body>
		</html>
	);
}
